/* =====================================================================
   extensions/fleet.sql — RYNEX Fleet module (multi-vehicle management)
   ---------------------------------------------------------------------
   Spec: Fleet Platform §51 (f2) — "Fleets + vehicle assignment".
   Shipper: src/Modules/Fleet/ (mounted at /api/v1/fleet via
            src/Router/modules.ts).

   Objects created here:
     TABLE fleets
       fleetId     VARCHAR(50) PK   (uuid, generated by the API)
       ownerUserId VARCHAR(50) NOT NULL FK -> users(userId)  [CASCADE]
       name        VARCHAR(100) NOT NULL
       createdAt   DATETIME2    DEFAULT SYSUTCDATETIME()

     TABLE fleetVehicles
       id         VARCHAR(50) PK   (server-generated NEWID())
       fleetId    VARCHAR(50) FK -> fleets(fleetId) ON DELETE CASCADE
       carId      VARCHAR(50) FK -> Cars(carId)     ON DELETE CASCADE
       assignedAt DATETIME2   DEFAULT SYSUTCDATETIME()
       UNIQUE (fleetId, carId)  <- duplicate assignment is impossible;
                                   spAssignVehicleToFleet converts the
                                   violation into THROW 50802.

     PROCEDURES (all CREATE OR ALTER, idempotent, SET NOCOUNT ON):
       spCreateFleet             (@FleetId, @OwnerUserId, @Name)
                                 -> inserts and returns the fleet row.
       SpGetFleetsByUser         (@OwnerUserId)
                                 -> the user's fleets + vehicleCount
                                    subquery, newest first.
       spGetFleet                (@FleetId)
                                 -> single fleet row INCLUDING
                                    ownerUserId — the controller uses
                                    this for the ownership check.
       spGetFleetVehicles        (@FleetId)
                                 -> fleet rows JOIN Cars: carId, model,
                                    brand, prices, pictureUrl.
       spAssignVehicleToFleet    (@FleetId, @CarId)
                                 -> car must exist (THROW 50801),
                                    fleet must exist (THROW 50803);
                                    duplicate assignment via the UNIQUE
                                    constraint -> THROW 50802.
       spRemoveVehicleFromFleet  (@FleetId, @CarId)
                                 -> idempotent delete; OUTPUTs the
                                    removed assignment row (empty
                                    recordset when nothing matched).
       spGetAllFleets            ()
                                 -> admin listing: every fleet JOIN
                                    users (userName) + vehicleCount.

   Error contract (numbers surface as node-mssql err.number; the fleet
   controller maps 50801/50803 -> 404, 50802 -> 409):
     50800  FleetId, OwnerUserId and Name are required
     50801  Car not found or unavailable
     50802  Vehicle already in fleet
     50803  Fleet not found

   OWNERSHIP MODEL (enforced in the API, data provided by spGetFleet):
     A fleet is private to its owner; admins bypass the check. The SPs
     deliberately take no user parameter — authorization lives in the
     controller so the same SP serves owner and admin paths.

   Idempotency:
     Tables are created only when missing (IF OBJECT_ID guards); all
     procedures use CREATE OR ALTER. No test EXECUTE statements — safe
     to re-run at any time.
   ---------------------------------------------------------------------
   Dependency:
     REQUIRES dbo.users and dbo.Cars from database/schema_tables.sql
     (that file always runs first via database/master.sql).
   ===================================================================== */

-- USE carshop;  -- optional: uncomment if not specifying the database via sqlcmd -d
GO

/* ---------------------------------------------------------------------
   1. fleets — one fleet per operator row (owner = users.userId)
   --------------------------------------------------------------------- */
IF OBJECT_ID(N'dbo.fleets', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.fleets
    (
        fleetId     VARCHAR(50)  NOT NULL
            CONSTRAINT PK_fleets PRIMARY KEY,
        ownerUserId VARCHAR(50)  NOT NULL,
        name        VARCHAR(100) NOT NULL,
        createdAt   DATETIME2    NOT NULL
            CONSTRAINT DF_fleets_createdAt DEFAULT (SYSUTCDATETIME()),

        CONSTRAINT FK_fleets_users FOREIGN KEY (ownerUserId)
            REFERENCES dbo.users (userId)
            ON DELETE CASCADE
    );
END;
GO

/* Owner lookup index for SpGetFleetsByUser. */
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = N'IX_fleets_ownerUserId' AND object_id = OBJECT_ID(N'dbo.fleets'))
BEGIN
    CREATE NONCLUSTERED INDEX IX_fleets_ownerUserId
        ON dbo.fleets (ownerUserId);
END;
GO

/* ---------------------------------------------------------------------
   2. fleetVehicles — assignment join (fleet <-> Cars catalogue)
   --------------------------------------------------------------------- */
IF OBJECT_ID(N'dbo.fleetVehicles', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.fleetVehicles
    (
        id         VARCHAR(50) NOT NULL
            CONSTRAINT PK_fleetVehicles PRIMARY KEY,
        fleetId    VARCHAR(50) NOT NULL,
        carId      VARCHAR(50) NOT NULL,
        assignedAt DATETIME2   NOT NULL
            CONSTRAINT DF_fleetVehicles_assignedAt DEFAULT (SYSUTCDATETIME()),

        CONSTRAINT FK_fleetVehicles_fleets FOREIGN KEY (fleetId)
            REFERENCES dbo.fleets (fleetId)
            ON DELETE CASCADE,
        CONSTRAINT FK_fleetVehicles_cars FOREIGN KEY (carId)
            REFERENCES dbo.Cars (carId)
            ON DELETE CASCADE,
        CONSTRAINT UQ_fleetVehicles_fleet_car UNIQUE (fleetId, carId)
    );
END;
GO

/* =====================================================================
   spCreateFleet
   Called by: POST /api/v1/fleet/fleets (createFleet)
   Payload from controller: { FleetId (uuid), OwnerUserId (token), Name }
   Inserts the fleet and returns the stored row (recordset[0]).
   The fleet id is generated by the API (uuid v4) so the caller can
   reference it immediately; the owner comes from the JWT, never from
   the request body.
   ===================================================================== */
CREATE OR ALTER PROCEDURE spCreateFleet
    @FleetId     VARCHAR(50),
    @OwnerUserId VARCHAR(50),
    @Name        VARCHAR(100)
AS
BEGIN
    SET NOCOUNT ON;

    IF @FleetId IS NULL OR LTRIM(RTRIM(@FleetId)) = ''
       OR @OwnerUserId IS NULL OR LTRIM(RTRIM(@OwnerUserId)) = ''
       OR @Name IS NULL OR LTRIM(RTRIM(@Name)) = ''
    BEGIN
        THROW 50800, 'FleetId, OwnerUserId and Name are required', 1;
    END;

    INSERT INTO dbo.fleets (fleetId, ownerUserId, name)
    VALUES (@FleetId, @OwnerUserId, LTRIM(RTRIM(@Name)));

    SELECT
        f.fleetId      AS fleetId,
        f.ownerUserId  AS ownerUserId,
        f.name         AS name,
        f.createdAt    AS createdAt,
        0              AS vehicleCount
    FROM dbo.fleets AS f
    WHERE f.fleetId = @FleetId;
END;
GO

/* =====================================================================
   SpGetFleetsByUser
   Called by: GET /api/v1/fleet/fleets (getMyFleets)
   Payload from controller: { OwnerUserId (token) }
   Returns the user's fleets, each with a vehicleCount subquery,
   newest first. Unknown/empty user -> empty recordset.
   ===================================================================== */
CREATE OR ALTER PROCEDURE SpGetFleetsByUser
    @OwnerUserId VARCHAR(50)
AS
BEGIN
    SET NOCOUNT ON;

    SELECT
        f.fleetId      AS fleetId,
        f.ownerUserId  AS ownerUserId,
        f.name         AS name,
        f.createdAt    AS createdAt,
        (SELECT COUNT(*)
         FROM dbo.fleetVehicles AS fv
         WHERE fv.fleetId = f.fleetId) AS vehicleCount
    FROM dbo.fleets AS f
    WHERE f.ownerUserId = @OwnerUserId
    ORDER BY f.createdAt DESC;
END;
GO

/* =====================================================================
   spGetFleet
   Called by: the fleet controller's ownership pre-check for every
              per-fleet route (GET/POST/DELETE .../fleets/:fleetId/...).
   Payload from controller: { FleetId }
   Returns the single fleet row INCLUDING ownerUserId — the controller
   compares it against the JWT userId (admins bypass). Unknown fleet ->
   empty recordset, which the controller maps to 404.
   ===================================================================== */
CREATE OR ALTER PROCEDURE spGetFleet
    @FleetId VARCHAR(50)
AS
BEGIN
    SET NOCOUNT ON;

    SELECT
        f.fleetId      AS fleetId,
        f.ownerUserId  AS ownerUserId,
        f.name         AS name,
        f.createdAt    AS createdAt,
        (SELECT COUNT(*)
         FROM dbo.fleetVehicles AS fv
         WHERE fv.fleetId = f.fleetId) AS vehicleCount
    FROM dbo.fleets AS f
    WHERE f.fleetId = @FleetId;
END;
GO

/* =====================================================================
   spGetFleetVehicles
   Called by: GET /api/v1/fleet/fleets/:fleetId/vehicles (getFleetVehicles)
   Payload from controller: { FleetId }
   Returns the fleet's assignments JOIN Cars (carId, model, brand,
   prices, pictureUrl), newest assignment first. Ownership is checked
   by the controller (spGetFleet) before this runs.
   ===================================================================== */
CREATE OR ALTER PROCEDURE spGetFleetVehicles
    @FleetId VARCHAR(50)
AS
BEGIN
    SET NOCOUNT ON;

    SELECT
        fv.id         AS id,
        fv.fleetId    AS fleetId,
        fv.carId      AS carId,
        fv.assignedAt AS assignedAt,
        c.model       AS model,
        c.brand       AS brand,
        c.prices      AS prices,
        c.pictureUrl  AS pictureUrl
    FROM dbo.fleetVehicles AS fv
    INNER JOIN dbo.Cars AS c
        ON c.carId = fv.carId
    WHERE fv.fleetId = @FleetId
    ORDER BY fv.assignedAt DESC;
END;
GO

/* =====================================================================
   spAssignVehicleToFleet
   Called by: POST /api/v1/fleet/fleets/:fleetId/vehicles (assignVehicle)
   Payload from controller: { FleetId, CarId }
   Behaviour:
     1. The fleet must exist (THROW 50803) — defence in depth; the
        controller has normally already 404'd via spGetFleet.
     2. The car must exist (THROW 50801). Soft-deleted cars are not
        assignable, mirroring spAddToCart's catalogue guard.
     3. Deduplication relies on the UNIQUE (fleetId, carId) constraint:
        the INSERT runs in a TRY block and the CATCH converts a
        duplicate-key violation (2627/2601 — includes the race between
        check and insert) into THROW 50802 'Vehicle already in fleet'.
     4. On success returns the assignment row joined with Cars
        (recordset[0]).
   ===================================================================== */
CREATE OR ALTER PROCEDURE spAssignVehicleToFleet
    @FleetId VARCHAR(50),
    @CarId   VARCHAR(50)
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;

    BEGIN TRY
        IF @FleetId IS NULL OR LTRIM(RTRIM(@FleetId)) = ''
           OR @CarId IS NULL OR LTRIM(RTRIM(@CarId)) = ''
        BEGIN
            THROW 50800, 'FleetId and CarId are required', 1;
        END;

        -- 1. The fleet must exist.
        IF NOT EXISTS (SELECT 1 FROM dbo.fleets WHERE fleetId = @FleetId)
        BEGIN
            THROW 50803, 'Fleet not found', 1;
        END;

        -- 2. The car must exist and must not be soft-deleted.
        IF NOT EXISTS (
            SELECT 1
            FROM dbo.Cars
            WHERE carId = @CarId
              AND ISNULL(isDeleted, 0) = 0
        )
        BEGIN
            THROW 50801, 'Car not found or unavailable', 1;
        END;

        -- 3. Insert; the UNIQUE (fleetId, carId) constraint is the
        --    dedupe backstop. 2627/2601 -> 50802 for the controller.
        BEGIN TRY
            INSERT INTO dbo.fleetVehicles (id, fleetId, carId)
            VALUES (CONVERT(VARCHAR(50), NEWID()), @FleetId, @CarId);
        END TRY
        BEGIN CATCH
            IF ERROR_NUMBER() IN (2627, 2601)
            BEGIN
                THROW 50802, 'Vehicle already in fleet', 1;
            END;
            THROW;  -- unrelated constraint/system error: rethrow as-is
        END CATCH;
    END TRY
    BEGIN CATCH
        THROW;  -- surface 50801/50802/50803 to the driver unchanged
    END CATCH;

    -- 4. The assignment row joined with Cars (only on success).
    SELECT
        fv.id         AS id,
        fv.fleetId    AS fleetId,
        fv.carId      AS carId,
        fv.assignedAt AS assignedAt,
        c.model       AS model,
        c.brand       AS brand,
        c.prices      AS prices,
        c.pictureUrl  AS pictureUrl
    FROM dbo.fleetVehicles AS fv
    INNER JOIN dbo.Cars AS c
        ON c.carId = fv.carId
    WHERE fv.fleetId = @FleetId
      AND fv.carId = @CarId;
END;
GO

/* =====================================================================
   spRemoveVehicleFromFleet
   Called by: DELETE /api/v1/fleet/fleets/:fleetId/vehicles/:carId
              (removeVehicle)
   Payload from controller: { FleetId, CarId }
   Idempotent: removes the assignment when present, silently no-ops
   when not (the controller still answers 200 'Vehicle removed').
   OUTPUTs the removed row (id, fleetId, carId, assignedAt) — an empty
   recordset means nothing was removed.
   ===================================================================== */
CREATE OR ALTER PROCEDURE spRemoveVehicleFromFleet
    @FleetId VARCHAR(50),
    @CarId   VARCHAR(50)
AS
BEGIN
    SET NOCOUNT ON;

    DELETE FROM dbo.fleetVehicles
    OUTPUT
        deleted.id         AS id,
        deleted.fleetId    AS fleetId,
        deleted.carId      AS carId,
        deleted.assignedAt AS assignedAt
    WHERE fleetId = @FleetId
      AND carId = @CarId;
END;
GO

/* =====================================================================
   spGetAllFleets
   Called by: GET /api/v1/fleet/fleets/all (getAllFleets — admin only;
              requireAdmin is enforced in fleet.router.ts).
   No parameters. Every fleet JOIN users (userName) with vehicleCount,
   newest first. LEFT JOIN keeps fleets whose owner row vanished.
   ===================================================================== */
CREATE OR ALTER PROCEDURE spGetAllFleets
AS
BEGIN
    SET NOCOUNT ON;

    SELECT
        f.fleetId      AS fleetId,
        f.ownerUserId  AS ownerUserId,
        u.userName     AS userName,
        f.name         AS name,
        f.createdAt    AS createdAt,
        (SELECT COUNT(*)
         FROM dbo.fleetVehicles AS fv
         WHERE fv.fleetId = f.fleetId) AS vehicleCount
    FROM dbo.fleets AS f
    LEFT JOIN dbo.users AS u
        ON u.userId = f.ownerUserId
    ORDER BY f.createdAt DESC;
END;
GO
